# Generated by Django 4.0.2 on 2022-02-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpsHandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vps',
            name='id',
        ),
        migrations.AlterField(
            model_name='vps',
            name='uid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
